images:
  veleroScheduleReplicator:
    repository: codejamninja/operators_velero-schedule-replicator
    tag: 0.0.2

config:
  clusterProvider: infrastructure
  imagePullPolicy: IfNotPresent
  updateStrategy: RollingUpdate
  veleroScheduleReplicator:
    baseUrl: ''
    hostname: ''
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
